""" Utility to remove Vietnamese specific characters from file names and titles
"""

VIETNAMESE_CHAR_MAP = {
    'a': 'a',
    'A': 'A',
    'à': 'a',
    'À': 'A',
    'ả': 'a',
    'Ả': 'A',
    'ã': 'a',
    'Ã': 'A',
    'á': 'a',
    'Á': 'A',
    'ạ': 'a',
    'Ạ': 'A',
    'ă': 'a',
    'Ă': 'A',
    'ằ': 'a',
    'Ằ': 'A',
    'ẳ': 'a',
    'Ẳ': 'A',
    'ẵ': 'a',
    'Ẵ': 'A',
    'ắ': 'a',
    'Ắ': 'A',
    'ặ': 'a',
    'Ặ': 'A',
    'â': 'a',
    'Â': 'A',
    'ầ': 'a',
    'Ầ': 'A',
    'ẩ': 'a',
    'Ẩ': 'A',
    'ẫ': 'a',
    'Ẫ': 'A',
    'ấ': 'a',
    'Ấ': 'A',
    'ậ': 'a',
    'Ậ': 'A',
    'b': 'b',
    'B': 'B',
    'c': 'c',
    'C': 'C',
    'd': 'd',
    'D': 'D',
    'đ': 'd',
    'Đ': 'D',
    'e': 'e',
    'E': 'E',
    'è': 'e',
    'È': 'E',
    'ẻ': 'e',
    'Ẻ': 'E',
    'ẽ': 'e',
    'Ẽ': 'E',
    'é': 'e',
    'É': 'E',
    'ẹ': 'e',
    'Ẹ': 'E',
    'ê': 'e',
    'Ê': 'E',
    'ề': 'e',
    'Ề': 'E',
    'ể': 'e',
    'Ể': 'E',
    'ễ': 'e',
    'Ễ': 'E',
    'ế': 'e',
    'Ế': 'E',
    'ệ': 'e',
    'Ệ': 'E',
    'f': 'f',
    'F': 'F',
    'g': 'g',
    'G': 'G',
    'h': 'h',
    'H': 'H',
    'i': 'i',
    'I': 'I',
    'ì': 'i',
    'Ì': 'I',
    'ỉ': 'i',
    'Ỉ': 'I',
    'ĩ': 'i',
    'Ĩ': 'I',
    'í': 'i',
    'Í': 'I',
    'ị': 'i',
    'Ị': 'I',
    'j': 'j',
    'J': 'J',
    'k': 'k',
    'K': 'K',
    'l': 'l',
    'L': 'L',
    'm': 'm',
    'M': 'M',
    'n': 'n',
    'N': 'N',
    'o': 'o',
    'O': 'O',
    'ò': 'o',
    'Ò': 'O',
    'ỏ': 'o',
    'Ỏ': 'O',
    'õ': 'o',
    'Õ': 'O',
    'ó': 'o',
    'Ó': 'O',
    'ọ': 'o',
    'Ọ': 'O',
    'ô': 'o',
    'Ô': 'O',
    'ồ': 'o',
    'Ồ': 'O',
    'ổ': 'o',
    'Ổ': 'O',
    'ỗ': 'o',
    'Ỗ': 'O',
    'ố': 'o',
    'Ố': 'O',
    'ộ': 'o',
    'Ộ': 'O',
    'ơ': 'o',
    'Ơ': 'O',
    'ờ': 'o',
    'Ờ': 'O',
    'ở': 'o',
    'Ở': 'O',
    'ỡ': 'o',
    'Ỡ': 'O',
    'ớ': 'o',
    'Ớ': 'O',
    'ợ': 'o',
    'Ợ': 'O',
    'p': 'p',
    'P': 'P',
    'q': 'q',
    'Q': 'Q',
    'r': 'r',
    'R': 'R',
    's': 's',
    'S': 'S',
    't': 't',
    'T': 'T',
    'u': 'u',
    'U': 'U',
    'ù': 'u',
    'Ù': 'U',
    'ủ': 'u',
    'Ủ': 'U',
    'ũ': 'u',
    'Ũ': 'U',
    'ú': 'u',
    'Ú': 'U',
    'ụ': 'u',
    'Ụ': 'U',
    'ư': 'u',
    'Ư': 'U',
    'ừ': 'u',
    'Ừ': 'U',
    'ử': 'u',
    'Ử': 'U',
    'ữ': 'u',
    'Ữ': 'U',
    'ứ': 'u',
    'Ứ': 'U',
    'ự': 'u',
    'Ự': 'U',
    'v': 'v',
    'V': 'V',
    'w': 'w',
    'W': 'W',
    'x': 'x',
    'X': 'X',
    'y': 'y',
    'Y': 'Y',
    'ỳ': 'y',
    'Ỳ': 'Y',
    'ỷ': 'y',
    'Ỷ': 'Y',
    'ỹ': 'y',
    'Ỹ': 'Y',
    'ý': 'y',
    'Ý': 'Y',
    'ỵ': 'y',
    'Ỵ': 'Y',
    'z': 'z',
    'Z': 'Z',
    ' ': '',
}


def remove_marks(marked):
    '''
    Remove Vietnamese specific characters with Latin characters for safe file
    names. Also remove spaces.
    '''
    cleaned = ''
    for character in marked:
        if character.isalnum():
            cleaned += character

    return ''.join(
        [VIETNAMESE_CHAR_MAP[i] if i in VIETNAMESE_CHAR_MAP else i for i in cleaned])


def main():
    """ Test method
    """
    print(remove_marks('Bèo dạt mây trôi chốn xa xôi Anh ơi em vẫn đợi bèo dạt'))


if __name__ == "__main__":
    main()
